apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
  {{- include "postgres-backup.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
{{- end }}
